print("Enter the 7 parameters a-->g")
a = float(input())
b = float(input())
c = float(input())
d = float(input())
e = float(input())
f = float(input())
g = float(input())

result = (a+b/c)/(d+e/(f+g))
print(result)